repos:
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.3
    hooks:
      - id: terraform-fmt
      - id: terraform-validate
      - id: tflint
      - id: shellcheck
      - id: gofmt
